version: '3.8'

services:
  db:
    image: mysql:lts
    restart: always
    container_name: PokeDB.Database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - '3306:3306'
    volumes:
      - ./PokeDB.Data/init/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./PokeDB.Data/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./PokeDB.Data/mysql:/var/lib/mysql # persist data by mounting volume

  server:
    build: ./PokeDB.Server
    container_name: PokeDB.Server
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=PokeDB
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - ASPNETCORE_URLS=http://+:80
    ports:
      - '5000:80' #Host:Container

  client:
    build: ./PokeDB.Client
    container_name: PokeDB.Client
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - '3000:80'
