@PokeDB.Server_HostAddress = http://localhost:5000

GET {{PokeDB.Server_HostAddress}}/api/ability
Accept: application/json
###

POST {{PokeDB.Server_HostAddress}}/api/pokemon
Content-Type: application/json

{
  "pokemonName": "Mew",
  "baseHp": 35,
  "baseAttack": 55,
  "baseDefense": 40,
  "typeName": "Electric",
  "abilityName": "Static",
  "moveNames": [
    "Tackle",
    "Thunder Shock"
  ],
  "previousEvolutionId": null,
  "previousEvolutionName": null
}

###

GET {{PokeDB.Server_HostAddress}}/api/pokemon

###

@id=1
GET {{PokeDB.Server_HostAddress}}/api/pokemon/{{id}}

###
